pipeline {
    agent any

    tools {
        maven 'Maven3'
        jdk 'JDK'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/PRANSHU9999/Wipro-Assignments'
            }
        }

        stage('Clean') {
            steps {
                dir('TutorialsNinja_Project') {
                    bat 'mvn clean'
                }
            }
        }

        stage('Compile') {
            steps {
                dir('TutorialsNinja_Project') {
                    bat 'mvn compile'
                }pipeline {
    agent any

    tools {
        maven 'Maven3'
        jdk 'JDK'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/PRANSHU9999/Wipro-Assignments'
            }
        }

        stage('Clean') {
            steps {
                dir('TutorialsNinja_Project') {
                    bat 'mvn clean'
                }
            }
        }

        stage('Compile') {
            steps {
                dir('TutorialsNinja_Project') {
                    bat 'mvn compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('TutorialsNinja_Project') {
                    bat 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('TutorialsNinja_Project') {
                    bat 'mvn package'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('TutorialsNinja_Project') {
                    bat 'docker build -t cucumber-framework .'
                }
            }
        }

        stage('Docker Run') {
            steps {
                dir('TutorialsNinja_Project') {
                    bat 'docker run --rm cucumber-framework'
                }
            }
        }
    }

    post {
        success {
            echo 'Build Successful'
        }

        failure {
            echo 'Build Failed'
        }
    }
}
            }
        }

        stage('Test') {
            steps {
                dir('TutorialsNinja_Project') {
                    bat 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('TutorialsNinja_Project') {
                    bat 'mvn package'
                }
            }
        }
    }

    post {
        success {
            echo 'Build Successful'
        }

        failure {
            echo 'Build Failed'
        }
    }
}